/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_sc.telas;


import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import projeto_sc.db.ModuloConexao;

/**
 *
 * @author ninguem
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblUsu = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        menuCad_Cli = new javax.swing.JMenuItem();
        menuCad_Os = new javax.swing.JMenuItem();
        menuCad_Usu = new javax.swing.JMenuItem();
        menuRel = new javax.swing.JMenu();
        menRelCli = new javax.swing.JMenuItem();
        menuRel_Serv = new javax.swing.JMenuItem();
        menuAju = new javax.swing.JMenu();
        menuAju_Sobre = new javax.swing.JMenuItem();
        menuOp = new javax.swing.JMenu();
        MenuOp_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de controle de OS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUsu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsu.setText("Usuário");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblData.setText("Data");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_sc/icones/rapid_logo4.png"))); // NOI18N

        menuCad.setText("Cadastro");

        menuCad_Cli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuCad_Cli.setText("Cliente");
        menuCad_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCad_CliActionPerformed(evt);
            }
        });
        menuCad.add(menuCad_Cli);

        menuCad_Os.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuCad_Os.setText("OS");
        menuCad_Os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCad_OsActionPerformed(evt);
            }
        });
        menuCad.add(menuCad_Os);

        menuCad_Usu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuCad_Usu.setText("Usuários");
        menuCad_Usu.setEnabled(false);
        menuCad_Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCad_UsuActionPerformed(evt);
            }
        });
        menuCad.add(menuCad_Usu);

        Menu.add(menuCad);

        menuRel.setText("Relátorio");
        menuRel.setEnabled(false);

        menRelCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        menRelCli.setText("Clientes");
        menRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelCliActionPerformed(evt);
            }
        });
        menuRel.add(menRelCli);

        menuRel_Serv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuRel_Serv.setText("Serviços");
        menuRel_Serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRel_ServActionPerformed(evt);
            }
        });
        menuRel.add(menuRel_Serv);

        Menu.add(menuRel);

        menuAju.setText("Ajuda");
        menuAju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjuActionPerformed(evt);
            }
        });

        menuAju_Sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        menuAju_Sobre.setText("Sobre");
        menuAju_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAju_SobreActionPerformed(evt);
            }
        });
        menuAju.add(menuAju_Sobre);

        Menu.add(menuAju);

        menuOp.setText("Opções");

        MenuOp_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuOp_Sair.setText("Sair");
        MenuOp_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOp_SairActionPerformed(evt);
            }
        });
        menuOp.add(MenuOp_Sair);

        Menu.add(menuOp);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsu)
                    .addComponent(lblData)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1269, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCad_OsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCad_OsActionPerformed
        // TODO add your handling code here:
        TelaOs tela_os = new TelaOs();
        tela_os.setVisible(true);
        desktop.add(tela_os);
    }//GEN-LAST:event_menuCad_OsActionPerformed

    private void menuAju_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAju_SobreActionPerformed
        // TODO add your handling code here:
        TelaAjuda sobre = new TelaAjuda();
        sobre.setVisible(true);
    }//GEN-LAST:event_menuAju_SobreActionPerformed

    private void MenuOp_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOp_SairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?",null, JOptionPane.YES_NO_OPTION);
        
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOp_SairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void menuAjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAjuActionPerformed

    private void menuCad_UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCad_UsuActionPerformed
        // TODO add your handling code here:
        TelaUsuario tela_usu = new TelaUsuario();
        tela_usu.setVisible(true);
        desktop.add(tela_usu);
        
    }//GEN-LAST:event_menuCad_UsuActionPerformed

    private void menuCad_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCad_CliActionPerformed
        // TODO add your handling code here:
        TelaCliente tela_cli = new TelaCliente();
        tela_cli.setVisible(true);
        desktop.add(tela_cli);
        
    }//GEN-LAST:event_menuCad_CliActionPerformed

    private void menRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelCliActionPerformed
        // TODO add your handling code here:
        //Gerando relatório de clientes.
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
            //Imprimindo relatório com o framework JasperReports
            try {
                //Usando a classe JasperPrint para preparar a impressão de um relatório
                JasperPrint print = JasperFillManager.fillReport("C:/reports/clientes.jasper", null, conexao);
                //A linha abaixo exibe o relatório através da classe JasperViewer
                JasperViewer.viewReport(print, false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelCliActionPerformed

    private void menuRel_ServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRel_ServActionPerformed
        // TODO add your handling code here:
        //Gerando relatório de serviços.
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão desse relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
            //Imprimindo relatório com o framework JasperReports
            try {
                //Usando a classe JasperPrint para preparar a impressão de um relatório
                JasperPrint print = JasperFillManager.fillReport("C:/reports/servicos.jasper", null, conexao);
                //A linha abaixo exibe o relatório através da classe JasperViewer
                JasperViewer.viewReport(print, false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menuRel_ServActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuOp_Sair;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsu;
    private javax.swing.JMenuItem menRelCli;
    private javax.swing.JMenu menuAju;
    private javax.swing.JMenuItem menuAju_Sobre;
    private javax.swing.JMenu menuCad;
    private javax.swing.JMenuItem menuCad_Cli;
    private javax.swing.JMenuItem menuCad_Os;
    public static javax.swing.JMenuItem menuCad_Usu;
    private javax.swing.JMenu menuOp;
    public static javax.swing.JMenu menuRel;
    private javax.swing.JMenuItem menuRel_Serv;
    // End of variables declaration//GEN-END:variables
}
